### ISSUE TITLE
Mapa 

### ISSUE THREAD

**Issue by CEOYuriPereira** [ViniciusHora1009/detetive_bot#1]
OI,adorei o projeto e sinto informar que ,quando clico no link para o Roll20 da como não autorizado, voce consegue me ajuda ?

**Comment by viniciushora** [comment]
Olá, CEOYuiPereira. Infelizmente este projeto é muito antigo e o Roll20 limitou o compartilhamento de mapas em modo público somente para os planos pagos, além de não ser mais possível copiar um jogo que não seja seu.

Dito isso, mudei as instruções para a aplicação do jogo. Disponibilizei a imagem do mapa do Roll20 em um drive, aí quem for utilizar pode pegar essa imagem e colocar no serviço de tabuleiro online que desejar. Eu recomendo o Roll20 porque se você preencher o espaço inteiro com o mapa, vai conseguir uma proporção perfeita de 1:1. As instruções de utilização do mapa estão no arquivo readme.

Obrigado por se interessar no projeto. Espero que consiga jogar com seus amigos.

**Comment by CEOYuriPereira** [comment]
Muito obrigado Vinícius , você é um herói

Em dom., 30 de abr. de 2023 11:46, Vinícius da Hora <
***@***.***> escreveu:

**Comment by viniciushora** [comment]
Sem problemas.

Como esse código é muito antigo, não estava mais rodando nas novas versões do Discord, mas agora atualizei o código no repositório e dei deploy da aplicação. O Bot está novamente online.
